# Generated by Django 2.1.2 on 2018-12-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrumuser',
            options={'ordering': ['nickname']},
        ),
        migrations.AddField(
            model_name='scrumgoal',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
