# Generated by Django 2.1.2 on 2018-12-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0002_auto_20181214_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrumgoal',
            options={'ordering': ['-id']},
        ),
    ]
